
name: Push-to-Production

on:
  push:
    branches:
      - 'master'

jobs:
  Deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: npm install
      - name: Run App
        run: |
            ls
            pm2 stop 1
            pm2 start 1
