name: Node CI

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Install npm dependencies
      run: npm install
    - name: Run App
      run: |
          ls
          pm2 stop 0
          pm2 start npm --name "collegeProject API" -- run start

